import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { availableLocalesMap, defaultLocale } from "@/next.locales.mjs";
import { getLocale } from "next-intl/server";
import { LocaleProvider } from "@/providers/localeProvider";
import { ThemeProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

interface Props {
	children: React.ReactNode;
	params: { locale: string };
}

export default async function RootLayout({ children, params: { locale } }: Readonly<Props>) {
	const fetchedLocale = await getLocale();

	const { langDir, hrefLang } = availableLocalesMap[fetchedLocale] || defaultLocale;

	return (
		<html className={inter.className} dir={langDir} lang={hrefLang}>
			<body suppressHydrationWarning className={inter.className}>
				<LocaleProvider>
					<ThemeProvider  attribute="class">{children}</ThemeProvider>
				</LocaleProvider>
			</body>
		</html>
	);
}
